name: Playground Child ðŸš

on:
  workflow_call:
    inputs:
      sampleMessage:
        type: string

env:
  SF_CLI_VERSION: "2.77.6"

jobs:
  playground-child-run:
    timeout-minutes: 10
    environment: "Minlopro DevHub"
    env:
      SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
      SF_CLI_VERSION: ${{ vars.SF_CLI_VERSION }}
      GHA_WORKFLOW_RUN_LINK: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "Check Input Variable"
        shell: bash
        run: |
          echo "Child Workflow running..."
          echo "inputs.sampleMessage -> ${{ inputs.sampleMessage }}"
          echo "vars.SF_CLI_VERSION -> ${{ vars.SF_CLI_VERSION }}"
          echo "secrets.SF_AUTH_URL -> ${{ secrets.SF_AUTH_URL }}"